steps:
# Test step for variable substitution
- name: 'ubuntu'
  args: ['cat', '.env']
#  env:
#  - 'BUILD=$BUILD_ID'
#  - 'PROJECT_ID=$PROJECT_ID'
#  - 'PROJECT_NUMBER=$PROJECT_NUMBER'
#  - 'REV=$REVISION_ID'

# Build the backend image
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/backend:latest', '-f', 'Dockerfile.backend', '.']

# Build the frontend image
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/frontend:latest', '-f', 'Dockerfile.frontend', '.']

# Push the backend image to Artifact Registry
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/${PROJECT_ID}/backend:latest']

# Push the frontend image to Artifact Registry
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/${PROJECT_ID}/frontend:latest']

## Substitute variables in Kubernetes manifests
#- name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    export GCP_PROJECT_ID=${_GCP_PROJECT_ID}
#    for file in kubernetes/*.yaml; do
#      envsubst < $file > $file.tmp && mv $file.tmp $file
#    done

# Deploy to GKE
#- name: 'gcr.io/cloud-builders/gke-deploy'
#  args:
#  - 'run'
#  - '--filename=kubernetes'
#  - '--location=${_GKE_CLUSTER_LOCATION}'
#  - '--cluster=${_GKE_CLUSTER_NAME}'

#substitutions:
#  _GKE_CLUSTER_NAME: 'cluster-gcp-uplift'
#  _GKE_CLUSTER_LOCATION: 'us-west1-a'
#  _GCP_PROJECT_ID: 'fierroolivares-462101'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '204160259354-compute@developer.gserviceaccount.com'
